function(add_binary_build_targets EXECUTABLE)
  get_filename_component(EXEC_NAME ${EXECUTABLE} NAME_WE)
  add_custom_target(build-hex DEPENDS ${EXECUTABLE} COMMAND ${CMAKE_OBJCOPY} -Oihex ${EXECUTABLE} ${EXEC_NAME}.hex)
  add_custom_target(build-bin DEPENDS ${EXECUTABLE} COMMAND ${CMAKE_OBJCOPY} -Obinary ${EXECUTABLE} ${EXEC_NAME}.bin)
endfunction()

function(add_target_size_print_targets TARGET)
    if(RUNTIME_OUTPUT_DIRECTORY)
        set(FILENAME "${RUNTIME_OUTPUT_DIRECTORY}/${TARGET}")
    else()
        set(FILENAME "${TARGET}")
    endif()
    add_custom_command(TARGET ${TARGET} POST_BUILD COMMAND ${CMAKE_SIZE_UTIL} ${FILENAME})
endfunction()